### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by angerangel** [zelurker/raine#15]
On linux I get:

```
Compiling source/neocd/cdrom.c...
In file included from source/mini-unzip/unzip.h:51:0,
                 from source/files.h:14,
                 from source/neocd/cdrom.c:8:
/usr/include/zlib.h:34:19: fatal error: zconf.h: File not found
 #include "zconf.h"
                   ^

```
What can I do?
The file exists, it's in:

```
/usr/include/x86_64-linux-gnu/zconf.h
/usr/lib/syslinux/com32/include/zconf.h

```

**Comment by zelurker** [comment]
this is an error from your own zlib ! It means there is a problem in your
zlib installation, it installed zlib.h but not zconf.h, or maybe there is a
symlink to zlib.h in /usr/include but not to zconf.h, in this case add a
symlink manually to all the zlib files in /usr/include.
Good luck !

2017-11-06 3:00 GMT+01:00 angerangel <notifications@github.com>:

**Comment by angerangel** [comment]
This helped me:

    cd /usr/include 
    sudo ln -s x86_64-linux-gnu/zconf.h
