### ISSUE TITLE
Compiling error: nasmw

### ISSUE THREAD

**Issue by angerangel** [zelurker/raine#17]
Hi,
on Linux now I get:

    Building table: done
    routine_counter = 7244
    Assembling linux-gnu-sdl/object/68000/s68000.asm...
    make: nasmw: command not found
    make: *** [linux-gnu-sdl/object/68000/s68000.o] Error 127

but nasmw is only for windows, linux has nasm. 
What's my mistake?

**Comment by zelurker** [comment]
Check that nasm is indeed installed. The makefile is not very clever, it
runs "nasm -v", if it doesn't get an answer it assumes nasm is installed as
nasmw and doesn't check. So you probably have a problem with your nasm
installation !


2017-11-28 0:07 GMT+01:00 angerangel <notifications@github.com>:

**Comment by angerangel** [comment]
Thank you, solved.
