### ISSUE TITLE
Binary dependendy wrong

### ISSUE THREAD

**Issue by angerangel** [zelurker/raine#19]
Hi,
on http://raine.1emulation.com/archive/debian/dists/unstable/main/binary-amd64/  there is the last binary http://raine.1emulation.com/archive/debian/dists/unstable/main/binary-amd64/neoraine_1.4.3_amd64.deb , however the dependency on ia32-libs is wrong, because now the version numbering of this library is with points. So the last version is **2014.05.14**, but the package asks for greater than **20120929** (without points), and this way can't be resolved.

**Comment by zelurker** [comment]
I don't even remember what this directory is for, but what is sure is that
neoraine has been outdated for years now.
The latest package is there :
http://raine.1emulation.com/archive/debian/dists/unstable/main/binary-i386/raine_0.64.13_i386.deb

For that it was either some tests to make a real amd64 version but in this
case it didn't go far, only some very simple games worked and it was
interesting only for developpers, or it was simply a mistake and nothing
should have gone to the amd64 directory (more likely).
This directory is not referenced when using the debian normal data files
anyway, you can reach it only manually.

2017-12-11 9:00 GMT+01:00 angerangel <notifications@github.com>:
