### ISSUE TITLE
Bogus detection of Gentoo system

### ISSUE THREAD

**Issue by pacho2** [zelurker/raine#21]
Currently compilation in Gentoo fails because it tries to built its own SDLmixer static copy. That is because it is using "uname -n" to detect a gentoo system. That is a bit tricky and, for example, in my computer doesn't report anything related with gentoo.

It would be better to detect the presence of the file /etc/gentoo-release

Thanks

**Comment by zelurker** [comment]
I am currently using gentoo too and don't have any problem. I don't
understand your sdl_mixer related problem... !
And I don't think it actually uses sdl_mixer, maybe you meant sdl_sound ?
It doesn't try to build sdl_sound, it tries to use
/usr/local/lib/libsdl_sound.a by default, it's just because if you want a
"good" sdl_sound, something able to read mp3s containing id3 tags without
crashing ridiculously, you need the unreleased version, the one in mercury.
So usually you build it manually and it ends up in /usr/local/lib, that's
why it tries to use this version first, and it uses a static version so
that if I release a binary, it's not lost.
Now you can either :
 - replace /usr/local/lib/libsdl_sound.a by -lSDL_sound knowing that the
default one will lack support for mp3s containing id3 tags, not a problem
if you don't use any neocd image with audio tracks in mp3.
 - build your own version manually of sdl_sound, it will end up in
/usr/local/lib
 - try to use the gentoo ebuild to create a sdl_sound using libmpg123,
that's the one needed for these id3 tags. I didn't try that but it should
work, in this case you can also replace in the makefile to use the standard
sdl_sound.

I hope I was clear enough, good luck !


2018-04-29 17:57 GMT+02:00 Pacho Ramos <notifications@github.com>:

**Comment by pacho2** [comment]
The error I get is:
`g++ -m32 -L /usr/lib32 -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -Wl,-z,noexecstack  -g -Wall -Wno-write-strings -o raine linux-gnu-sdl/object/games/ainferno.o linux-gnu-sdl/object/games/aquajack.o linux-gnu-sdl/object/games/arabianm.o linux-gnu-sdl/object/games/arkanoid.o linux-gnu-sdl/object/games/arkretrn.o linux-gnu-sdl/object/games/armedf.o linux-gnu-sdl/object/games/ashura.o linux-gnu-sdl/object/games/asuka.o linux-gnu-sdl/object/games/biomtoy.o linux-gnu-sdl/object/games/bloodbro.o linux-gnu-sdl/object/games/bonzeadv.o linux-gnu-sdl/object/games/bshark.o linux-gnu-sdl/object/games/bsystem.o linux-gnu-sdl/object/games/bubblem.o linux-gnu-sdl/object/games/bublbobl.o linux-gnu-sdl/object/games/bubl_mcu.o linux-gnu-sdl/object/games/bubsymph.o linux-gnu-sdl/object/games/cabal.o linux-gnu-sdl/object/games/cadash.o linux-gnu-sdl/object/games/cave.o linux-gnu-sdl/object/games/chaknpop.o linux-gnu-sdl/object/games/chasehq2.o linux-gnu-sdl/object/games/chasehq.o linux-gnu-sdl/object/games/cleofort.o linux-gnu-sdl/object/games/contcirc.o linux-gnu-sdl/object/games/cookbib.o linux-gnu-sdl/object/games/cps1drv.o linux-gnu-sdl/object/games/cps2drv.o linux-gnu-sdl/object/games/crimec.o linux-gnu-sdl/object/games/crospang.o linux-gnu-sdl/object/games/ctribebl.o linux-gnu-sdl/object/games/cupfinal.o linux-gnu-sdl/object/games/dangarb.o linux-gnu-sdl/object/games/darius2d.o linux-gnu-sdl/object/games/darius.o linux-gnu-sdl/object/games/dariusg.o linux-gnu-sdl/object/games/deadconx.o linux-gnu-sdl/object/games/diverboy.o linux-gnu-sdl/object/games/dkong.o linux-gnu-sdl/object/games/dleague.o linux-gnu-sdl/object/games/doubled3.o linux-gnu-sdl/object/games/eaction2.o linux-gnu-sdl/object/games/earthjkr.o linux-gnu-sdl/object/games/esd16.o linux-gnu-sdl/object/games/exzisus.o linux-gnu-sdl/object/games/f3demo.o linux-gnu-sdl/object/games/fchamp.o linux-gnu-sdl/object/games/flstory.o linux-gnu-sdl/object/games/frogger.o linux-gnu-sdl/object/games/galpanic.o linux-gnu-sdl/object/games/gcpball.o linux-gnu-sdl/object/games/gekridan.o linux-gnu-sdl/object/games/gridseek.o linux-gnu-sdl/object/games/gunbird.o linux-gnu-sdl/object/games/gunlock.o linux-gnu-sdl/object/games/hitice.o linux-gnu-sdl/object/games/hthero95.o linux-gnu-sdl/object/games/hyperpcb.o linux-gnu-sdl/object/games/intcup94.o linux-gnu-sdl/object/games/kaiserkn.o linux-gnu-sdl/object/games/konamigx.o linux-gnu-sdl/object/games/koshien.o linux-gnu-sdl/object/games/ksystem.o linux-gnu-sdl/object/games/ktiger2.o linux-gnu-sdl/object/games/landmakr.o linux-gnu-sdl/object/games/lightbr.o linux-gnu-sdl/object/games/lsystem.o linux-gnu-sdl/object/games/macrossp.o linux-gnu-sdl/object/games/masterw.o linux-gnu-sdl/object/games/matmania.o linux-gnu-sdl/object/games/mcatadv.o linux-gnu-sdl/object/games/megasys1.o linux-gnu-sdl/object/games/metalb.o linux-gnu-sdl/object/games/mitchell.o linux-gnu-sdl/object/games/mugsmash.o linux-gnu-sdl/object/games/neogeo.o linux-gnu-sdl/object/games/ninjak.o linux-gnu-sdl/object/games/ninjaw.o linux-gnu-sdl/object/games/nmk.o linux-gnu-sdl/object/games/nmk004.o linux-gnu-sdl/object/games/opwolf3.o linux-gnu-sdl/object/games/opwolf.o linux-gnu-sdl/object/games/othunder.o linux-gnu-sdl/object/games/pbobble2.o linux-gnu-sdl/object/games/pbobble3.o linux-gnu-sdl/object/games/pbobble4.o linux-gnu-sdl/object/games/pengo.o linux-gnu-sdl/object/games/pirates.o linux-gnu-sdl/object/games/popnpop.o linux-gnu-sdl/object/games/psyforce.o linux-gnu-sdl/object/games/puchicar.o linux-gnu-sdl/object/games/quizgame.o linux-gnu-sdl/object/games/rainbow.o linux-gnu-sdl/object/games/rambo3.o linux-gnu-sdl/object/games/rastan2.o linux-gnu-sdl/object/games/rastan.o linux-gnu-sdl/object/games/recordbr.o linux-gnu-sdl/object/games/ridefght.o linux-gnu-sdl/object/games/ringrage.o linux-gnu-sdl/object/games/robokid.o linux-gnu-sdl/object/games/seta.o linux-gnu-sdl/object/games/silentd.o linux-gnu-sdl/object/games/silkworm.o linux-gnu-sdl/object/games/spacegun.o linux-gnu-sdl/object/games/spcinv95.o linux-gnu-sdl/object/games/superchs.o linux-gnu-sdl/object/games/syvalion.o linux-gnu-sdl/object/games/taito_f2.o linux-gnu-sdl/object/games/tecmosys.o linux-gnu-sdl/object/games/terrac.o linux-gnu-sdl/object/games/terraf.o linux-gnu-sdl/object/games/tetrisp2.o linux-gnu-sdl/object/games/tetrist.o linux-gnu-sdl/object/games/toaplan1.o linux-gnu-sdl/object/games/toaplan2.o linux-gnu-sdl/object/games/toki.o linux-gnu-sdl/object/games/topland.o linux-gnu-sdl/object/games/topspeed.o linux-gnu-sdl/object/games/trstars.o linux-gnu-sdl/object/games/twinqix.o linux-gnu-sdl/object/games/undrfire.o linux-gnu-sdl/object/games/upl.o linux-gnu-sdl/object/games/viofight.o linux-gnu-sdl/object/games/volfied.o linux-gnu-sdl/object/games/warriorb.o linux-gnu-sdl/object/games/wgp.o linux-gnu-sdl/object/games/wrestlef.o linux-gnu-sdl/object/games/wwfsstar.o linux-gnu-sdl/object/games/xsystem1.o linux-gnu-sdl/object/games/xsystem2.o linux-gnu-sdl/object/games/zerozone.o linux-gnu-sdl/object/games/f3system.o linux-gnu-sdl/object/games/nichisnd.o linux-gnu-sdl/object/games/taitosnd.o linux-gnu-sdl/object/games/tchnosnd.o linux-gnu-sdl/object/games/kick_mcu.o linux-gnu-sdl/object/games/tc200obj.o linux-gnu-sdl/object/games/tc003vcu.o linux-gnu-sdl/object/games/cps1.o linux-gnu-sdl/object/games/tc100scn.o linux-gnu-sdl/object/games/tc140syt.o linux-gnu-sdl/object/games/setax1.o linux-gnu-sdl/object/games/tc110pcr.o linux-gnu-sdl/object/games/tc002obj.o linux-gnu-sdl/object/games/taito_z.o linux-gnu-sdl/object/games/tc150rod.o linux-gnu-sdl/object/games/kiki_mcu.o linux-gnu-sdl/object/games/tc180vcu.o linux-gnu-sdl/object/games/tc005rot.o linux-gnu-sdl/object/games/tc004vcu.o linux-gnu-sdl/object/games/tc006vcu.o linux-gnu-sdl/object/games/tc220ioc.o linux-gnu-sdl/object/games/tc101scn.o linux-gnu-sdl/object/games/gun.o linux-gnu-sdl/object/68000/s68000.o linux-gnu-sdl/object/68000/starhelp.o linux-gnu-sdl/object/68020/newcpu.o linux-gnu-sdl/object/68020/readcpu.o linux-gnu-sdl/object/68020/cpustbl.o linux-gnu-sdl/object/68020/cpudefs.o linux-gnu-sdl/object/68020/a020core.o linux-gnu-sdl/object/z80/mz80.o linux-gnu-sdl/object/z80/mz80help.o linux-gnu-sdl/object/6502/m6502.o linux-gnu-sdl/object/6502/m6502hlp.o linux-gnu-sdl/object/m68705/m68705.o linux-gnu-sdl/object/sound/assoc.o linux-gnu-sdl/object/sdl/dialogs/sound_commands.o linux-gnu-sdl/object/sdl/dialogs/neocd_options.o linux-gnu-sdl/object/sdl/dialogs/neo_softdips.o linux-gnu-sdl/object/sdl/dialogs/neo_debug_dips.o linux-gnu-sdl/object/sdl/dialogs/translator.o linux-gnu-sdl/object/sound/ym2151.o linux-gnu-sdl/object/sound/2151intf.o linux-gnu-sdl/object/sound/2203intf.o linux-gnu-sdl/object/sound/2413intf.o linux-gnu-sdl/object/sound/ym2413.o linux-gnu-sdl/object/sound/2610intf.o linux-gnu-sdl/object/emudx.o linux-gnu-sdl/object/cat93c46.o linux-gnu-sdl/object/decode.o linux-gnu-sdl/object/cps2crpt.o linux-gnu-sdl/object/sound/3812intf.o linux-gnu-sdl/object/sound/adpcm.o linux-gnu-sdl/object/sound/ay8910.o linux-gnu-sdl/object/sound/dac.o linux-gnu-sdl/object/sound/dxsmp.o linux-gnu-sdl/object/sound/es5506.o linux-gnu-sdl/object/sound/m6585.o linux-gnu-sdl/object/sound/msm5205.o linux-gnu-sdl/object/sound/namco.o linux-gnu-sdl/object/sound/qsound.o linux-gnu-sdl/object/sound/smp16bit.o linux-gnu-sdl/object/sound/ymz280b.o linux-gnu-sdl/object/sound/ymf278b.o linux-gnu-sdl/object/sound/x1_010.o linux-gnu-sdl/object/sound/toaplan2.o linux-gnu-sdl/object/video/tilemod.o linux-gnu-sdl/object/video/palette.o linux-gnu-sdl/object/video/priorities.o linux-gnu-sdl/object/video/newspr.o linux-gnu-sdl/object/video/spr64.o linux-gnu-sdl/object/video/cache.o linux-gnu-sdl/object/video/res.o linux-gnu-sdl/object/video/scale2x.o linux-gnu-sdl/object/video/scale3x.o linux-gnu-sdl/object/video/i386/str/6x8_8.o linux-gnu-sdl/object/video/i386/str/6x8_16.o linux-gnu-sdl/object/video/i386/str/6x8_32.o linux-gnu-sdl/object/video/i386/16x8_8.o linux-gnu-sdl/object/video/i386/16x8_16.o linux-gnu-sdl/object/video/i386/16x8_32.o linux-gnu-sdl/object/video/i386/blit_x2/8.o linux-gnu-sdl/object/video/i386/blit_x2/16.o linux-gnu-sdl/object/video/i386/blit_x2/24.o linux-gnu-sdl/object/video/i386/blit_x2/32.o linux-gnu-sdl/object/video/zoom/16x16.o linux-gnu-sdl/object/video/zoom/16x16_16.o linux-gnu-sdl/object/video/zoom/16x16_32.o linux-gnu-sdl/object/video/zoom/16x8.o linux-gnu-sdl/object/video/c/lscroll.o linux-gnu-sdl/object/video/alpha.o linux-gnu-sdl/object/video/c/str_opaque.o linux-gnu-sdl/object/video/c/common.o linux-gnu-sdl/object/video/c/pdraw.o linux-gnu-sdl/object/video/hq2x16.o linux-gnu-sdl/object/video/hq2x32.o linux-gnu-sdl/object/video/hq3x16.o linux-gnu-sdl/object/video/hq3x32.o linux-gnu-sdl/object/video/i386/spr8x8_8.o linux-gnu-sdl/object/video/i386/spr8_16.o linux-gnu-sdl/object/video/i386/spr8_32.o linux-gnu-sdl/object/video/i386/16x16_8.o linux-gnu-sdl/object/video/i386/16x16_16.o linux-gnu-sdl/object/video/i386/16x16_32.o linux-gnu-sdl/object/video/i386/packed/8.o linux-gnu-sdl/object/video/i386/packed/16.o linux-gnu-sdl/object/video/i386/packed/32.o linux-gnu-sdl/object/video/i386/32x32_8.o linux-gnu-sdl/object/video/i386/32x32_16.o linux-gnu-sdl/object/video/i386/32x32_32.o linux-gnu-sdl/object/video/i386/newspr2/8.o linux-gnu-sdl/object/video/i386/newspr2/16.o linux-gnu-sdl/object/video/i386/newspr2/32.o linux-gnu-sdl/object/video/i386/move.o linux-gnu-sdl/object/video/c/sprites32_a50.o linux-gnu-sdl/object/video/c/mapped_alpha.o linux-gnu-sdl/object/sound/ymdeltat.o linux-gnu-sdl/object/sound/fmopl.o linux-gnu-sdl/object/sound/fm.o linux-gnu-sdl/object/sound/emulator.o linux-gnu-sdl/object/raine.o linux-gnu-sdl/object/romdir.o linux-gnu-sdl/object/hiscore.o linux-gnu-sdl/object/history.o linux-gnu-sdl/object/ingame.o linux-gnu-sdl/object/savegame.o linux-gnu-sdl/object/arpro.o linux-gnu-sdl/object/bld.o linux-gnu-sdl/object/debug.o linux-gnu-sdl/object/config.o linux-gnu-sdl/object/confile.o linux-gnu-sdl/object/files.o linux-gnu-sdl/object/newmem.o linux-gnu-sdl/object/cpuid.o linux-gnu-sdl/object/cpumain.o linux-gnu-sdl/object/emumain.o linux-gnu-sdl/object/demos.o linux-gnu-sdl/object/timer.o linux-gnu-sdl/object/soundcfg.o linux-gnu-sdl/object/speed_hack.o linux-gnu-sdl/object/savepng.o linux-gnu-sdl/object/loadroms.o linux-gnu-sdl/object/bezel.o linux-gnu-sdl/object/sdl/dsw.o linux-gnu-sdl/object/sdl/png.o linux-gnu-sdl/object/sdl/SDL_gfx/SDL_framerate.o linux-gnu-sdl/object/sdl/SDL_gfx/SDL_rotozoom.o linux-gnu-sdl/object/sdl/SDL_gfx/SDL_gfxPrimitives.o linux-gnu-sdl/object/mini-unzip/unzip.o linux-gnu-sdl/object/mini-unzip/ioapi.o linux-gnu-sdl/object/mame/memory.o linux-gnu-sdl/object/mame/eeprom.o linux-gnu-sdl/object/7z/7zAlloc.o linux-gnu-sdl/object/7z/7zBuf2.o linux-gnu-sdl/object/7z/7zBuf.o linux-gnu-sdl/object/7z/7zCrc.o linux-gnu-sdl/object/7z/7zCrcOpt.o linux-gnu-sdl/object/7z/7zDec.o linux-gnu-sdl/object/7z/7zFile.o linux-gnu-sdl/object/7z/7zIn.o linux-gnu-sdl/object/7z/7zStream.o linux-gnu-sdl/object/7z/Bcj2.o linux-gnu-sdl/object/7z/Bra86.o linux-gnu-sdl/object/7z/Bra.o linux-gnu-sdl/object/7z/CpuArch.o linux-gnu-sdl/object/7z/LzmaDec.o linux-gnu-sdl/object/7z/Ppmd7.o linux-gnu-sdl/object/7z/Ppmd7Dec.o linux-gnu-sdl/object/7z/Lzma2Dec.o linux-gnu-sdl/object/7z/7zMain.o linux-gnu-sdl/object/sdl/gui.o linux-gnu-sdl/object/sdl/dialogs/video_info.o linux-gnu-sdl/object/sdl/dialogs/fsel.o linux-gnu-sdl/object/sdl/dialogs/video_options.o linux-gnu-sdl/object/sdl/dialogs/sound_options.o linux-gnu-sdl/object/sdl/dialogs/gui_options.o linux-gnu-sdl/object/sdl/dialogs/dirs.o linux-gnu-sdl/object/sdl/dialogs/about.o linux-gnu-sdl/object/sdl/dialogs/messagebox.o linux-gnu-sdl/object/sdl/dialogs/controls.o linux-gnu-sdl/object/sdl/dialogs/cheats.o linux-gnu-sdl/object/sdl/dialogs/game_options.o linux-gnu-sdl/object/sdl/dialogs/sprite_viewer.o linux-gnu-sdl/object/sdl/dialogs/colors.o linux-gnu-sdl/object/sdl/gui/tfont.o linux-gnu-sdl/object/sdl/gui/menu.o linux-gnu-sdl/object/sdl/gui/widget.o linux-gnu-sdl/object/sdl/gui/tslider.o linux-gnu-sdl/object/sdl/gui/tedit.o linux-gnu-sdl/object/sdl/gui/tlift.o linux-gnu-sdl/object/sdl/gui/tbitmap.o linux-gnu-sdl/object/sdl/console/console.o linux-gnu-sdl/object/sdl/console/parser.o linux-gnu-sdl/object/sdl/console/scripts.o linux-gnu-sdl/object/sdl/console/if.o linux-gnu-sdl/object/sdl/gui/tconsole.o linux-gnu-sdl/object/sdl/console/exec.o linux-gnu-sdl/object/sdl/dialogs/game_selection.o linux-gnu-sdl/object/sdl/dialogs/romdirs.o linux-gnu-sdl/object/sdl/dialogs/dlg_dsw.o linux-gnu-sdl/object/games/games.o linux-gnu-sdl/object/games/default.o linux-gnu-sdl/object/sdl/blit.o linux-gnu-sdl/object/sdl/display.o linux-gnu-sdl/object/sdl/winpos.o linux-gnu-sdl/object/sdl/compat.o linux-gnu-sdl/object/sdl/control.o linux-gnu-sdl/object/sdl/opengl.o linux-gnu-sdl/object/math/matrix.o linux-gnu-sdl/object/sdl/glsl.o linux-gnu-sdl/object/sdl/profile.o linux-gnu-sdl/object/sdl/gen_conv.o linux-gnu-sdl/object/sdl/sasound.o -lz -L/usr/lib64 -lpng16 -lm -lGL -lGLU -lmuparser -lSDL -lpthread -lSDL_ttf -lSDL_image  /usr/local/lib/libSDL_sound.a -lFLAC -lvorbisfile
g++: error: /usr/local/lib/libSDL_sound.a: No such file or directory
make: *** [makefile:1227: raine] Error 1`

and I thought that it was failing to detect that I was compiling on Gentoo because makefile uses "uname -n" to try to get "Gentoo" from there... but in my computer is:
$ uname -n
dell-2017
(my hostname)

Changing makefile in this way to force it to use -lSDL_sound works:
`--- a/makefile.old      2018-04-29 17:52:38.883282664 +0200
+++ b/makefile  2018-04-29 17:57:45.671968935 +0200
@@ -1112,13 +1112,9 @@
 # but since debian doesn't seem to package the right sdl-sound version 6
 # months after asking, I'll link my static version instead, which asks all
 # the libs debian wants... way too many, but anyway...
-ifeq ("$(shell uname -n)","gentoo")
 # or the one for gentoo, just link SDL_sound directly !
 LIBS += -lSDL_sound
 else
-LIBS += /usr/local/lib/libSDL_sound.a -lFLAC -lvorbisfile
-endif
-else
 # windows
 # and these libs are used by SDL_sound/FLAC
 LIBS += -logg -lvorbisfile -lws2_32 -lintl`

Well, it fails a bit later but because it seems it needs other libs in Gentoo to provide 32 bits support:
https://bugs.gentoo.org/654336

**Comment by zelurker** [comment]
lol, I hadn't even noticed there was a very outdated ebuild for raine in
gentoo !

Oh well sorry for misunderstanding, now I booted my linux and so I can
reply while reading the makefile.
This uname -n is just a hack to allow building on my main computer whose
hostname is gentoo that's all.
the other machine builds the raine debian package and uses the static
sd_sound.

If you really want an ebuild out of this, I guess you should make a patch
to keep only the -lSDL_sound version, and put something somewhere to tell
it's adviced to have the libsdl_sound which uses libmpg123 for mp3, which
is not the last official binary.

That's the only place with a problem in the makefile and that's only
because the author of sdl_sound never released an official version with
mpg123 support in it although it's totally stable.
Except that, I had some trouble building a 386 version of muparser using
the standard ebuild from gentoo, so here too I built it manually and just
installed the /usr/lib32/libmuparser.so.2.2.4. At that time this ebuild
didn't allow to change ABI_X86, I don't think it changed.

If I remember correctly these are the 2 only problems I had with gentoo.
The other problem is that it's gonna have a ton of 386 dependancies if you
build it from source on a system which uses almost no 386 package, but I
see no solution to this.


2018-04-29 21:30 GMT+02:00 Pacho Ramos <notifications@github.com>:

**Comment by pacho2** [comment]
Yeah, is really outdated as games team don't have enough manpower for it. I will try to see if muparser maintainers can provide the multilib support for the ebuild. Regarding the check, I think that it would be better to check for /etc/gentoo-release file instead of that uname... that way the upstream package don't need to be patched so much to build. Also in the ebuild attached to the bug you will see some other fixes we are carrying downstream and that seem to be still needed for latest version ;)

**Comment by zelurker** [comment]
do you talk about the 3 patch files in files for this ebuild ?
They were all included in latest version afaik, but the makefile also
changed quite a lot.
I guess you know that already but the latest versions can be found in git
there : https://github.com/zelurker/raine
And this 0.51.9 was already in git, but it didn't have any tag, there is
0.51.6 and 0.51.11 though. For 0.51.9 it was still the time the sources
were going to the download page, stopped doing that long ago because not
enough people needed the sources (almost noone actually).

I'd love to have the -lSDL_sound for the standard makefile but it's
dangerous for me, it's a sure way to forget to change it when building a
binary and bye to the right mp3 support. I'd try to find something cleaner
than what there is now though... !

**Comment by pacho2** [comment]
Yes, the patch I was thinking is the LDFLAGS one:
	# Respect LDFLAGS
	sed -i -e 's/$(LDV) $(LFLAGS)/$(LDV) $(LDFLAGS) $(LFLAGS)/' makefile || die

Because the other changes look to me like something more for downstream to change the location of the installed files... then, probably only the LDFLAGS one is needed

**Comment by zelurker** [comment]
Ok, added the LDFLAGS to git, and now I use /usr/local/lib/libSDL_sound.a
only if it exists, it should fix everything.
It's on git head.


2018-04-30 9:08 GMT+02:00 Pacho Ramos <notifications@github.com>:

**Comment by pacho2** [comment]
Thanks a lot!

**Comment by zelurker** [comment]
This was updated lately again, but this issue is outdated, closing it...
