### ISSUE TITLE
Compilation error with gcc 8.1.0

### ISSUE THREAD

**Issue by seadra** [zelurker/raine#22]
The latest stable gcc gives the following error:

> source/sdl/dialogs/about.cpp:786:15: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
  { EMUNAME" "VERSION" (c)1998-2015 " HANDLE, NULL, NULL },

**Comment by zelurker** [comment]
Sorry, 8.1 is unstable for gentoo.
Even for debian testing, they use gcc-7.2 (and 7.2 and 7.3 are marked as
testing in gentoo).
Too early to do some tests with this, that's what happens when you use too
recent stuff...

2018-05-26 0:53 GMT+02:00 seadra <notifications@github.com>:

**Comment by seadra** [comment]
Arch Linux based distros have all migrated to 8.1 FYI.

**Comment by zelurker** [comment]
Too bad, I only test on gentoo and debian. I guess it uses c++ 2011
standard by default, there is probably a command line option to disable
that, so you would need to add this to the CFLAGS to compile it. Or just
wait... !



2018-05-26 17:09 GMT+02:00 seadra <notifications@github.com>:

**Comment by zelurker** [comment]
I guess this one was fixed long ago now, using gcc-9.2.0 from arch... closing issue...
