### ISSUE TITLE
SDL:1.2.15 is redundant now days

### ISSUE THREAD

**Issue by Ntemis** [zelurker/raine#27]
I love the work being done here and i would like to bring it to more people hands to put to a good use
But using such an old sdl version make it one way for all the emulation community that has been established.
This project is unusable for linux retro distros usage as it is which is a big shame.
If there is anything that can be done for this would be a great step forward.
Best Regards

**Comment by zelurker** [comment]
unusable ? Why ? I use linux as my dev platform, debian first, then gentoo
and now arch, and compiled raine all the time on all these platforms.
Plus it's a lot easier to compile in 64 bits, but sdl is not an issue
anywhere anyway.
But I agree it would be nice to have sdl2 support, now it's easier said
than done...

**Comment by Ntemis** [comment]
The real problem is on distros turnkey's for retro emulation.
Our cross compiling framework dont allow for such old sdl version to be used.
Fyi we are currently on sdl 2.0.14 and asap 16 is out we will be using that

**Comment by Ntemis** [comment]
I saw the current progress with great joy. Well done.
Is there any chance for arm/aarch64 dynarecs(jit)?
