### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by Felipefpl** [zelurker/raine#29]
1 - I have the option to select brazilian portuguese but the translation isnt applied because the locale isnt there.

2 - It sucks to have to download a separate package to make raine work, please embed the packages inside the compressed files.

**Comment by zelurker** [comment]
Lol, I see only 1 problem here, the fact that the pt locale didn't make it
to the compressed zip file for windows binary !
Actually it wasn't even installed in the makefile (through make install).
Fixed in git.
Yeah ok, I'll make another zip file, sorry !

**Comment by Felipefpl** [comment]
> Lol, I see only 1 problem here, the fact that the pt locale didn't make it to the compressed zip file for windows binary ! Actually it wasn't even installed in the makefile (through make install). Fixed in git. Yeah ok, I'll make another zip file, sorry ! Le dim. 1 août 2021 

thanks for fixing but the zip file i mentioned is here http://raine.1emulation.com/download/latest.html - why download the dlls in a extra package if they are all needed? Better embed in the release, it's what everyone who has to deal with such dlls do. ;)

**Comment by zelurker** [comment]
Because obviously these dlls stay the same for almost all the versions, so
it's just some disk space waste + bandwidth waste if you include them in
all the releases.
You just have to install them once, after that the updates go to the same
directory where the dlls are already installed.

**Comment by zelurker** [comment]
As a last remark on that, it's also the linux way of doing things. In linux, all these libraries are installed and handled by the system, the raine package just tells it needs them that's all. In windows since there is no package management, the shared libs are a real mess. Here I agree that 2M is not much these days and I could include them in the binary packages, but it's still 2M completely wasted, and there were quite a lot of binary packages released... !

**Comment by Felipefpl** [comment]
> As a last remark on that, it's also the linux way of doing things. In linux, all these libraries are installed and handled by the system, the raine package just tells it needs them that's all. In windows since there is no package management, the shared libs are a real mess. Here I agree that 2M is not much these days and I could include them in the binary packages, but it's still 2M completely wasted, and there were quite a lot of binary packages released... !

I understand, thanks for the explanation, but if this is too annoying to deal with you should call someone to help you to make windows packages. ;)

**Comment by zelurker** [comment]
Found nobody for that, and I am probably going to stop now anyway...
Strangely in all these years, nobody wanted to help about windows. Atani
tried 1st to make a windows version in the very early day of the open
source raine, but he tried with visual studio and lost all interest when
things started to work by using mingw32 ! It's the last person who took any
interest in the windows version !
