### ISSUE TITLE
Linux is not supported?

### ISSUE THREAD

**Issue by Ntemis** [zelurker/raine#31]
make CROSSCOMPILE=1
Building Raine, Fully optimized version with gcc for linux-gnu CPU=pentium3
dependencies : if you get an error here, install the required dev package
libpng:1.6.37
SDL:2.0.10
Compiling source/neocd/pd4990a.c...
cc1: error: CPU you selected does not support x86-64 instruction set
cc1: error: ‘-fcf-protection=full’ is not supported for this target
make: *** [makefile:1430: linux-gnu-sdl2/object/neocd/pd4990a.o] Error 1

**Comment by zelurker** [comment]
Why not visiting the forums there :
https://www.1emulation.com/forums/forum/126-raine/ ?
and I updated the notes on how to compile, and there is a section on cross
compiling, see there :
https://www.1emulation.com/forums/topic/36609-raine-0925/?do=findComment&comment=364241
And the subject is bad, it's not supporting linux, it's about cross
compiling
