### ISSUE TITLE
At build time, make is ignoring redefinition of ShareDir, and Bindir.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [zelurker/raine#35]
Make is ignoring redefinition of Sharedir and Bindir, this is to facilitate raine being built into an RPM where %{buildroot} is used.

**Comment by zelurker** [comment]
I'd say your package build system is obsolete, it should not require such
variables in the makefile (it's not the case in arch).
The least you could do is try to open a pull request for something so
useless... !

Le sam. 26 mars 2022 à 01:27, Zombie-Ryushu ***@***.***> a
écrit :
