### ISSUE TITLE
Build error:'SDL_GetAudioDeviceSpec' was not declared in this scope

### ISSUE THREAD

**Issue by Zombie-Ryushu** [zelurker/raine#36]
[  256s] source/sdl/dialogs/sound_options.cpp: In function 'void init_sound_driver(int)':
[  256s] source/sdl/dialogs/sound_options.cpp:102:6: error: 'SDL_GetAudioDeviceSpec' was not declared in this scope
[  256s]       SDL_GetAudioDeviceSpec(i,0,&spec);
[  256s]       ^~~~~~~~~~~~~~~~~~~~~~
[  256s] source/sdl/dialogs/sound_options.cpp:102:6: note: suggested alternative: 'SDL_GetAudioDeviceName'
[  256s]       SDL_GetAudioDeviceSpec(i,0,&spec);
[  256s]       ^~~~~~~~~~~~~~~~~~~~~~
[  256s]       SDL_GetAudioDeviceName
[

**Comment by zelurker** [comment]
Requires SDL2-2.0.16, you know this is currently 2.0.20, 2.0.16 is quite old already... !
2.0.16:
---------------------------------------------------------------------------
General:
* Added SDL_FlashWindow() to get a user's attention
* Added SDL_GetAudioDeviceSpec() to get the preferred audio format of a device
