### ISSUE TITLE
black screen with "-nogui"

### ISSUE THREAD

**Issue by lepascalou** [zelurker/raine#4]
Hi,

I'm using RAINE (git version) under archlinux, and when launching a game with "-n" option I get a black screen (but game is launched: I can hear the coin insert and the game effects) until I call the gui with "tab" or toggle fullscreen/window mode with "alt-return"; then the screen is redrawn correctly.

I tried to disable/enable glsl shaders, change the displaymodes, but still same problem. I also tried RAINE v. 0.64.5, and same symptoms occur.  

Is there any more information that would be helpful?

SDL is version 1.2.15, my system is x86_64, gcc 5.2.0

Anyway, this is a _great_ emulator!

Pascal

**Comment by zelurker** [comment]
Français encore alors ?
Apparemment c'est spécifique à la sortie opengl, en choisissant yuv overlay
avant ça marche.
J'étais pas au courant, je regarderai + tard...

2015-11-02 20:46 GMT+01:00 lepascalou notifications@github.com:

**Comment by zelurker** [comment]
Fixed in git

**Comment by lepascalou** [comment]
That was fast! Quelle réactivité, merci pour le fix!
