### ISSUE TITLE
Any intention to make libretro port?

### ISSUE THREAD

**Issue by SumavisionQ5** [zelurker/raine#46]
Nowadays RetroArch is very polular in the world, and MAME and FinalBurn Neo/Alpha all have their own libretro ports. 
Compared to FinalBurn Neo and MAME, Raine has its own features, such as better performance on Tatio F3 emulation, mp3 support for NeoGeo CD emulation and so on. 
So, is it possible to make a libretro port? 
I think it would make more people to enjoy this old but good emulator. 
Thanks.

**Comment by zelurker** [comment]
Not currently. Raine has a lot of settings which would be lost if doing that, like the sound associations to replace a song ingame by an external song. But anybody is welcome to try to do one !
