### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tacerus** [zelurker/raine#48]
Hello!

I want to package Raine, but could not find any license information in the repository. Is there a chance you could add an [SPDX](https://spdx.org/licenses/) compatible license?

**Comment by zelurker** [comment]
Yeah well raine includes quite some other packages with their licenses so I
never sorted this out.
For the 32 bits version the 68000, z80, and 6502 emulators are free for non
commercial use, but they are very old now, their respective authors are
almost impossible to contact. For the 68020, it's some code extracted from
uae, I am not sure which license they use, probably gpl but not totally
sure.
For the 64 bits version, 68000 & 68020 '(Musashi) has a license included in
its sources and its documentation. the z80 & 6502 are from mame but before
they switched to the gpl, so I am not sure.
As you see it's quite messy.

**Comment by zelurker** [comment]
... and the sh2 : free for non commercial use, original author credited in the about dialog and in the readme.txt file included in the gens_sh2 directory.
Closing this...

**Comment by tacerus** [comment]
Thank you for the detailed responses.
