### ISSUE TITLE
Raine 0.94.8 - some strings remain untranslated even after being added the possibility to translate them

### ISSUE THREAD

**Issue by Felipefpl** [zelurker/raine#55]
This happens not only in about box but in a few other places too:

![Sem título](https://user-images.githubusercontent.com/5569804/210148863-1f6b59c0-320d-4606-8a8d-da45257b522c.gif)

**Comment by zelurker** [comment]
Works for me, no idea what you did (but from what is displayed on your
picture, december 21 is too old for the about dialog, the new translations
were added yesterday for this one !).

[image: raine.png]

**Comment by Felipefpl** [comment]
I added the updated .mo file to raine, no idea why this happens.

Edit - updated from latest .pot file and the c-format problem is still there. :/

**Comment by zelurker** [comment]
1) as I said you need an updated binary, it's not just about updating the translation
2) sorry I didn't update the .pot file yet because you didn't reply about the sort option for the pot file, as I said it was sorted alphabetically so far and maybe it's better to sort by file to get some context. But it will make a totally different file... Maybe I'll keep the old sort then, I guess it doesn't really matter. Idea about that ?

**Comment by zelurker** [comment]
And for some reason when I import a picture like above in gmail, it doesn't show in github, but it worked before, no idea why it doesn't anymore... oh well... !

**Comment by Felipefpl** [comment]
Where can i download an updated binary? I mean. i got the latest one from the site http://raine.1emulation.com/download/latest.html (btw, it's a good idea to have both binaries/dlls merged in a single package, it's only 6,82 MBs when i compress both with 7zip, i'm talking about the 32 bit version)

Regarding the .pot file i suggest to choose the option that is the best for you. ;)

**Comment by zelurker** [comment]
You should really try to compile your own version, there is a good guide on
the site for that, a few people followed it without problem and without
being experts, and it would be useful just to test translations when the
binary is updated like here. Meanwhile I guess I can send a binary by mail,
32 bits you said, you'll have just the bare binary, place the data files
where they should...

For the sort option, not sure yet, I'll have to experiment... ! If you
install your own compilation tools you'll be able to create this raine.pot
file easily by the way.

gmail won't let me put an exe in an attachment even if renamed, so here is
the link : http://raine.1emulation.com/archive/tux/raine.7z
I have included an updated raine.pot with the new sort option, experiment
with it !

**Comment by Felipefpl** [comment]
Tried your version and everything works fine now including the translation file, thanks for you help. :+1:
