### ISSUE TITLE
Feature Requests - Support for Graphic Enhancements

### ISSUE THREAD

**Issue by Felipefpl** [zelurker/raine#68]
It would be nice if raine had a system to multiply the resolutions of the game like duckstation/pcsx 2 has. Also i noticed that raine supports hq2x but not hq3x and hq4x. Why is that?

I saw too that 4xbr/5xbr are supported but not 2xbr/3xbr (those are the xbrz filters am i correct?) It would be nice to have support for those. After all, i doubt all those other filters available are used since those are the best ones.

**Comment by zelurker** [comment]
Patches welcome... !

**Comment by zelurker** [comment]
hq2x was used only for normal blits with versions for sdl1 which included these normal blits.
With the latest sdl2 version all this is done through shaders only, normal blits disappeared totally, so all this becomes irrelevant for now. Closing the issue.
