### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by tomyun** [zelurker/raine#7]
FYI, a Homebrew formula is now up in its games tap: Homebrew/homebrew-games#502
 `muparser` formula is also updated to support universal binary: Homebrew/homebrew#49059

OS X users may simply install Raine by typing `brew install homebrew/games/raine`.

**Comment by zelurker** [comment]
Thanks, I cc this to Romain who helped to build the latest osx build !

2016-02-16 23:43 GMT+01:00 Kyungdahm Yun notifications@github.com:

**Comment by zelurker** [comment]
Ho that’s great !!! Any idea if it could be integrated into Openemu too ?

Romain
