### ISSUE TITLE
Messed up layers

### ISSUE THREAD

**Issue by henriqueccruz** [zelurker/raine#9]
Hi guys, I'm not sure how to troubleshoot this.

It seems like I can't get the fixed layer to be transparent on Neo Geo CD. Parts where it's supposed to be transparent are all black. If the whole layer is supposed to be transparent, all I can see is a black screen. I disable the layer in the options and I can see the game running beautifully. It doesn't happen on NeoGeo, though. Emulator compiles just fine, everything runs smoothly. 

Any directions?

**Comment by zelurker** [comment]
On which game exactly, and do you do something special about this layer ?
Normally everything displays fine without doing anything...

2016-05-08 10:13 GMT+02:00 rickhessmann notifications@github.com:

**Comment by henriqueccruz** [comment]
I'm playing Last Resort, problem occurs both in Japanese and World versions. I can't even get KOF '97 (JP) to start, for some reason (App crashes). Ninja Commando starts and plays just fine.

If it helps, I'm using DaemonTools image format (.cue, .ccd, .sub and .img files). Am I missing something?

**Comment by rickhessmann** [comment]
Ninja Commando starts and plays just fine.

**Comment by zelurker** [comment]
You know there is a region switch for neocd, so getting the "japenese"
version isn't really relevant here, you can change the region to whatever
you like in the emu. Well all I can say is that I played these games and
they work fine. Are you sure about your backups ?
Try those from gametronik they are guaranteed good.
http://www.gametronik.com/site/emulation/neogeocd/

Even if the site is in french you should find easily the games from this
page (click on the 1st letter).

2016-05-08 23:28 GMT+02:00 rickhessmann notifications@github.com:

**Comment by henriqueccruz** [comment]
Downloaded Last Resort from this site. Unfortunately, I have the very same issue. I'll try to download the compiled software. Perhaps I'm having some weird issue with libpng.

**Comment by henriqueccruz** [comment]
Probably something with my compilation. Downloaded version worked just fine.
KOF '97 problem persists. I'll open another ticket.
